add remapping surface area test
CliMA/ClimaCoupler.jl pull request #114
Opened 2022-09-07 00:07 UTC by juliasloan25

# PULL REQUEST

## Purpose and Content
Add a unit test to check that `LandSeaMask` remapping is conservative with respect to the surface area of the planet. Also change the remapping code to be monotone by default, removing the need for a `clean_mask` function.

## PR Checklist
- [ ] This PR has a corresponding issue OR is linked to an SDI.
- [ ] I have followed CliMA's codebase [contribution](https://clima.github.io/ClimateMachine.jl/latest/Contributing/) and [style](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) guidelines OR N/A.
- [ ] I have followed CliMA's [documentation policy](https://github.com/CliMA/policies/wiki/Documentation-Policy).
- [ ] I have checked all issues and PRs and I certify that this PR does not duplicate an open PR.
- [ ] I linted my code on my local machine prior to submission OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code used in an integration test OR N/A.
- [ ] All tests ran successfully on my local machine OR N/A.
- [ ] All classes, modules, and function contain docstrings OR N/A.
- [ ] Documentation has been added/updated OR N/A.

2022-09-08 14:37 UTC, LenkaNovak requested changes
Good job, @juliasloan25 ! I left a couple of comments. Also, for the Buildkite runs, looks like you're using Nq 5 with the `mono` flag, which isn't enabled in TempestRemap yet. Can you change `--nh_poly` to 4, in the driver like you had before? Hopefully that'll fix it.

2022-09-08 14:37 UTC, LenkaNovak commented on experiments/AMIP/moist_mpi_earth/coupler_utils/regridder.jl
> +        # in_np and mono arguments ensure mapping is conservative and monotone
I would also comment here that np_in = dof = polynomial degree + 1

2022-09-08 14:37 UTC, LenkaNovak commented on experiments/AMIP/moist_mpi_earth/coupler_utils/unit_tester.jl
> +test_conservation_ncdataset()
Do you mean `test_surfacearea_ones()` ?

2022-09-09 02:26 UTC, juliasloan25 commented
bors try

2022-09-09 21:03 UTC, juliasloan25 commented
bors try

2022-09-13 21:13 UTC, LenkaNovak approved these changes

2022-09-13 21:13 UTC, LenkaNovak commented
@juliasloan25 all is passing now and it's calling your CC commit for the `mono` flag. I will update the Manifest to the release version in a separate PR when we do other upgrades. After you've addressed the remaining issues above, feel free to squash and bors r+.

2022-09-13 23:24 UTC, juliasloan25 commented
bors r+

2022-09-14 00:10 UTC, merged